# These are supported funding model platforms
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom:
  - "bitcoin:bc1qjaet6jgpk08la46jelmlpgsz84luc4lc0tnwr5"
