/*
 * tests/hlse_config_fuzz.c
 *
 * Fuzz harness for the --config file parser, which consumes a
 * fully untrusted user-supplied file (key = value lines, comments,
 * quoting, daemon keys).
 *
 * Function exercised:
 *   hlse_config_load(path, cfg, err, cap)
 *
 * The parser needs a real file on disk, so each iteration writes the
 * generated bytes to a mkstemp file, runs the parser, then unlinks it.
 *
 * Build (plain):
 *   gcc -O0 -g -Wall -Wextra -D_POSIX_C_SOURCE=200809L \
 *       -o tests/fuzz_config tests/hlse_config_fuzz.c \
 *       hlse_config.c -I.
 * Build (ASan):
 *   gcc -O1 -g -Wall -Wextra -D_POSIX_C_SOURCE=200809L \
 *       -fsanitize=address,undefined \
 *       -o tests/fuzz_config_asan tests/hlse_config_fuzz.c \
 *       hlse_config.c -I.
 *
 * Usage: ./tests/fuzz_config [iterations] [seed]
 */

#define _POSIX_C_SOURCE 200809L

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <setjmp.h>
#include <time.h>
#include <unistd.h>
#include <fcntl.h>
#include "../hlse_config.h"

static jmp_buf crash_jmp;
static char    last_input[4096];
static size_t  last_input_len;

static void crash_handler(int sig) { (void)sig; longjmp(crash_jmp, 1); }

static unsigned long xorshift(unsigned long *s) {
    unsigned long x = *s;
    x ^= x << 13; x ^= x >> 7; x ^= x << 17;
    *s = x; return x;
}

/* ── Input generators ─────────────────────────────────────────────────── */

static size_t gen_random(char *buf, size_t cap, unsigned long *rng) {
    size_t len = xorshift(rng) % 512;
    if (len >= cap) len = cap - 1;
    size_t i;
    for (i = 0; i < len; i++) buf[i] = (char)(xorshift(rng) & 0xFF);
    buf[len] = '\0';
    return len;
}

/* key=value-ish lines drawn from the real key space plus junk */
static size_t gen_kv(char *buf, size_t cap, unsigned long *rng) {
    static const char *keys[] = {
        "json", "sarif", "quiet", "syslog", "fingerprints",
        "git-history", "fail-on", "from", "baseline", "log-file",
        "patterns", "watch", "scan-interval", "pid-file",
        "JSON", " json ", "", "key with space", "\xff", NULL
    };
    static const char *vals[] = {
        "true", "false", "0", "1", "yes", "no", "on", "off",
        "alert", "block", "isolate", "log", "safe", "42", "-1",
        "9999999999999999999", "/tmp/x", "\"quoted path\"",
        "a b c", "", "\t", "=", "#c", NULL
    };
    int nk = 0; while (keys[nk]) nk++;
    int nv = 0; while (vals[nv]) nv++;
    size_t len = 0;
    int lines = 1 + (int)(xorshift(rng) % 5);
    int l;
    for (l = 0; l < lines && len + 1200 < cap; l++) {
        const char *k = keys[xorshift(rng) % (unsigned long)nk];
        const char *v = vals[xorshift(rng) % (unsigned long)nv];
        int w = snprintf(buf + len, cap - len, "%s%s%s%s\n",
                         xorshift(rng) % 3 ? "# " : "",
                         k,
                         xorshift(rng) % 4 ? "=" : "  ",
                         v);
        if (w < 0) break;
        len += (size_t)w;
    }
    buf[len] = '\0';
    return len;
}

/* extreme lines: overlong keys/values, NULs inside, no newline at EOF */
static size_t gen_edge(char *buf, size_t cap, unsigned long *rng) {
    size_t len = 0;
    switch (xorshift(rng) % 4) {
        case 0: {  /* 4000-char key */
            size_t i;
            for (i = 0; i < 4000 && len < cap - 8; i++)
                buf[len++] = (char)('a' + xorshift(rng) % 26);
            len += (size_t)snprintf(buf + len, cap - len, "=1\n");
            break;
        }
        case 1: {  /* 4000-char value */
            len += (size_t)snprintf(buf + len, cap - len, "watch=");
            size_t i;
            for (i = 0; i < 4000 && len < cap - 2; i++)
                buf[len++] = '/';
            break;
        }
        case 2:   /* embedded NUL between key and value */
            len += (size_t)snprintf(buf + len, cap - len, "json");
            buf[len++] = '\0';
            len += (size_t)snprintf(buf + len, cap - len, "=true\n");
            break;
        default:  /* no trailing newline, then a second key */
            len += (size_t)snprintf(buf + len, cap - len,
                                   "quiet=true\nsarif");
            break;
    }
    buf[len] = '\0';
    return len;
}

/* ── Exercise ─────────────────────────────────────────────────────────── */

static void exercise(const char *buf, size_t len) {
    char tmpl[] = "/tmp/hlse_cfg_fuzz_XXXXXX";
    int fd = mkstemp(tmpl);
    if (fd < 0) return;
    if (write(fd, buf, len) < 0) { /* partial writes fine — fuzz input */ }
    close(fd);

    {
        HlseConfig cfg;
        char err[256];
        memset(&cfg, 0, sizeof(cfg));
        (void)hlse_config_load(tmpl, &cfg, err, sizeof(err));
    }
    unlink(tmpl);
}

/* ── Main ─────────────────────────────────────────────────────────────── */

typedef size_t (*gen_fn)(char *, size_t, unsigned long *);

int main(int argc, char **argv) {
    long iterations = (argc > 1) ? atol(argv[1]) : 100000;
    unsigned long seed = (argc > 2) ? (unsigned long)atol(argv[2]) : 0xBADC0DEUL;
    if (seed == 0) seed = (unsigned long)time(NULL);

    printf("HLSE Config-Parser Fuzz Harness\n");
    printf("  iterations: %ld\n  seed:       0x%lx\n\n", iterations, seed);

    struct sigaction sa;
    sa.sa_handler = crash_handler;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = 0;
    sigaction(SIGSEGV, &sa, NULL);
    sigaction(SIGBUS,  &sa, NULL);
    sigaction(SIGFPE,  &sa, NULL);
    sigaction(SIGABRT, &sa, NULL);

    gen_fn generators[] = {
        gen_random,
        gen_kv,
        gen_edge,
    };
    const int n_gen = (int)(sizeof(generators) / sizeof(generators[0]));

    long crashes = 0, ok = 0;
    char buf[4096];
    unsigned long rng = seed;

    long i;
    for (i = 0; i < iterations; i++) {
        int g = (int)(xorshift(&rng) % (unsigned long)n_gen);
        size_t len = generators[g](buf, sizeof(buf), &rng);

        last_input_len = len < sizeof(last_input) ? len : sizeof(last_input) - 1;
        memcpy(last_input, buf, last_input_len);
        last_input[last_input_len] = '\0';

        if (setjmp(crash_jmp) == 0) {
            exercise(buf, len);
            ok++;
        } else {
            crashes++;
            fprintf(stderr, "CRASH at iter %ld (gen %d)\n", i, g);
            fprintf(stderr, "  input (%zu bytes): ", last_input_len);
            fwrite(last_input, 1, last_input_len < 80 ? last_input_len : 80, stderr);
            fprintf(stderr, "\n");
        }
    }

    printf("results: %ld ok, %ld crashed\n", ok, crashes);
    return crashes > 0 ? 1 : 0;
}
